// <auto-generated />
namespace RGECMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fee));
        
        string IMigrationMetadata.Id
        {
            get { return "202004091019496_fee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
